// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookReviewController from "./book_review_controller"
application.register("book-review", BookReviewController)

import BookSearchController from "./book_search_controller"
application.register("book-search", BookSearchController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PdfMetadataController from "./pdf_metadata_controller"
application.register("pdf-metadata", PdfMetadataController)
