// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import BookReviewController from "controllers/book_review_controller"
application.register("book-review", BookReviewController)

import BookSearchController from "controllers/book_search_controller"
application.register("book-search", BookSearchController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import PdfMetadataController from "controllers/pdf_metadata_controller"
application.register("pdf-metadata", PdfMetadataController)
